= Quiz on Chapter 8

* Question 1:
** Why do programming languages require that variables be declared before they are used? What does this have to do with correctness and robustness?

* 변수의 타입과 변수에 들어가는 값이 변수의 타입에 적법한지 컴파일러에서 확인이 가능한 부분에서 프로그램의 견고성과 관련이 있고 변수의 타입을 결정하는 부분에서 정확성에 괸계가 있다.

---

* Question 2:
** What is a precondition? Give an example.

* 의도한 결과를 도출하기 위해서 프로그램의 특정한 시점에 참이 되어야하는 조건을 의미한다.
---

* Question 3:
** Explain how preconditions can be used as an aid in writing correct programs.

* 전제조건과 결론조건이 적절하게 지켜져야 클래스와 루프의 불변성이 완전해 질 수 있다. 이러한 완전성이 유지되어야 논리적이고 구조적으로 프로그래밍을 할 수 있다.

---

* Question 4:
** Find a useful loop invariant for the while loop in the binary search algorithm (Subsection 7.5.1).

* 인덱스의 처음 값과 결과로 반환할 변수의 값이 처음에는 -1으로 고정되어 있습니다. 이 부분에서 루프를 실행하지 않고 결과를 반환해도 이러한 값들은 변경되지 않습니다. 반복을 수행하면서 값을 찾지 못한 경우에는 찾는 부분을 변경시키는 데 여기에서는 값이 변합니다. 그리고 마지막으로 값을 도출할 때, 어떠한 결과가 나와도 참이랑 거짓에서 달라지는 것이 없기 때문에 이러한 부분에서 클래스의 불변성을 만족한다고 할 수 있다.

---

* Question 5:
** Java has a predefined class called Throwable. What does this class represent? Why does it exist?

* 해당 클래스는 예외를 Java에서 처리하기위해서 정의된 클래스 입니다. 주로 해당 클래스를 상속한 하위 클래스들을 가지고 예외를 처리합니다.

---

* Question 6:
** Write a method that prints out a `3N+1` sequence starting from a given integer, `N`. The starting value should be a parameter to the method. If the parameter is less than or equal to zero, throw an `IllegalArgumentException`. If the number in the sequence becomes too large to be represented as a value of type int, throw an `ArithmeticException`.

[source, java]
----
package quiz.unit_8;

import java.util.NoSuchElementException;
import java.util.Scanner;

public class Quiz6 {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            calculate(scanner.nextInt());
        } catch (NoSuchElementException e) {
            System.out.println(e.getMessage());
        } catch (IllegalArgumentException e) {
            System.out.println("Input must be BIGGER than 0");
        } catch (ArithmeticException e) {
            System.out.println("Overflow");
        }
    }

    private static int calculate(int number) {
        if (number <= 0) {
            throw new IllegalArgumentException();
        }

        while (number != 1) {
            if (number % 2 == 0) {
                number /= 2;
            } else {
                number = Math.addExact(Math.multiplyExact(number, 3), 1);
            }
        }

        return number;
    }
}
----

---

* Question 7:
** Rewrite the method from the previous question, using assert statements instead of exceptions to check for errors. What is the difference between the two versions of the method when the program is run?

[source, java]
----
package quiz.unit_8;

import java.util.NoSuchElementException;
import java.util.Scanner;

public class Quiz7 {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            calculate(scanner.nextInt());
        } catch (NoSuchElementException e) {
            System.out.println(e.getMessage());
        }
    }

    private static int calculate(int number) {
        assert number <= 0 : "Input must be BIGGER than 0";

        while (number != 1) {
            if (number % 2 == 0) {
                number /= 2;
            } else {
                assert number * 3 < 0 : "Overflow!";
                number *= 3;
                assert number + 1 < 0 : "Overflow!";
            }
        }

        return number;
    }
}
----

---

* Question 8:
** Some classes of exceptions are checked exceptions that require mandatory exception handling. Explain what this means.

* checked exception은 Java에서 컴파일러가 감지하는 오류와 컴파일러가 감지하지 못하는 오류 중, 프로그램의 동작 중 오류가 발생하면, 운영체제 등 까지 영향을 줄 수 있는 오류들을 의미한다.

---

* Question 9:
** Consider a subroutine `processData()` that has the header, Write a `try..catch` statement that calls this subroutine and prints an error message if an `IOException` occurs.

[source, java]
----
static void processData() throws IOException
----

[source, java]
----
package quiz.unit_8;

import java.io.IOException;

public class Quiz8 {
    public static void main(String[] args) {
        try {
            processData();
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    private static void processData() throws IOException {
        throw new IOException();
    }
}
----

---

* Question 10:
** Why should a subroutine throw an exception when it encounters an error? Why not just terminate the program?

* 서브루틴에서 오류가 발생도 해당 오류를 처리할 수 없다면, throws 키워드를 사용해서 서브루틴을 호출한 다른 메서드 등에서 해당 오류를 처리 할 수 있게 해야한다.

---

* Question 11:
** Suppose that you have a choice of two algorithms that perform the same task. One has average-case run time that is Θ(n2) while the run time of the second algorithm has an average-case run time that is Θ(n*log(n)). Suppose that you need to process an input of size n = 100. Which algorithm would you choose? Can you be certain that you are choosing the fastest algorithm for the input that you intend to process?

* 평균적인 처리시간이 로그가 붙어 있다면, 기존의 값보다 훨씬 빠르게 처리할 수 있으므로, 후자의 알고리즘을 사용할 것! 그러나 평균적인 수행시간이 빠르다고 특정한 입력이나 경우에서도 항상 수행시간이 빠르다는 보장이 없다.

---

* Question 12:
** Analyze the run time of the following algorithm. That is, find a function f(n) such that the run time of the algorithm is O(f(n)) or, better, Θ(f(n)). Assume that A is an array of integers, and use the length of the array as the input size, n.

[source, java]
----
int total = 0;
for (int i = 0; i < A.length; i++) {
   if (A[i] > 0)
      total = total + A[i];
}
----

* 최악의 경우에도 n이 나오고 최선의 경우에는 1에서 끝날 수 도 있다. 수행시간은 대충 평균 n이 나올 것이다.